image:
  repository: 666834592660.dkr.ecr.eu-central-1.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_HOST: my-app-postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
  ALLOWED_HOSTS: "ac585d121a9424a308fb1a4e7c8fea61-117942717.eu-central-1.elb.amazonaws.com"

