replicaCount: 2

image:
  repository: 666834592660.dkr.ecr.eu-central-1.amazonaws.com/lesson-9-django-app
  pullPolicy: Always
  tag: "16"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

config:
  SECRET_KEY: "django-insecure-u(qc9*j0w=ut5db3f#izfz_8szd7rruds!p8p5hgwz0in=+s7t"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_DB: "project"
  POSTGRES_USER: "myuser"
  POSTGRES_PASSWORD: "mypassword"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

postgres:
  enabled: true
  storage: 10Gi
  storageClassName: gp2

nodeSelector: {}
tolerations: []
affinity: {}